name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    name: Check
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.4.1
        with:
          distribution: 'adopt-openj9'
          java-version: 11
      - name: Assembling app debug flavor
        run: ./gradlew :app:assembleDebug
      - name: run jvm unit tests
        run: ./gradlew test
